export const jobsData = [
    {
      id: 1,
      title: "在庫管理",
      salary: "1000-1200",
      japaneseLevel: 3,
      location: "Tokyo",
      distance: 2.5,
      image: "images\在庫管理.png",
      tags: ["軽作業", "作業服が支給されます"],
    },
    {
      id: 2,
      title: "レストランのシェフ",
      salary: "1200-1500",
      japaneseLevel: 2,
      location: "Osaka",
      distance: 1.8,
      image: "images\レストランのシェフ.jpg",
      tags: ["マカロン", "料理を作る"],
    },
    {
      id: 3,
      title: "コンビニスタッフ",
      salary: "1100-1300",
      japaneseLevel: 3,
      location: "Fukuoka",
      distance: 0.5,
      image: "images\コンビニスタッフ.jfif",
      tags: ["深夜勤務可", "交通費支給"],
    },
    {
      id: 4,
      title: "工場作業員",
      salary: "1300-1600",
      japaneseLevel: 1,
      location: "Nagoya",
      distance: 3.2,
      image: "images\工場作業員.jpg",
      tags: ["体力仕事", "寮完備"],
    },
    {
      id: 5,
      title: "ホテル清掃",
      salary: "1050-1250",
      japaneseLevel: 2,
      location: "Kyoto",
      distance: 1.2,
      image: "images\ホテル.jpg",
      tags: ["朝勤務", "ユニフォーム貸与"],
    },
    {
      id: 6,
      title: "デリバリードライバー",
      salary: "1400-1800",
      japaneseLevel: 2,
      location: "Sapporo",
      distance: 4.0,
      image: "images\デリバリードライバー.png",
      tags: ["車両貸与", "歩合給あり"],
    },
    {
      id: 7,
      title: "介護ヘルパー",
      salary: "1250-1450",
      japaneseLevel: 3,
      location: "Kobe",
      distance: 2.1,
      image: "images\介護ヘルパー.jpg",
      tags: ["資格取得支援", "研修あり"],
    },
    {
      id: 8,
      title: "建設現場作業",
      salary: "1500-2000",
      japaneseLevel: 1,
      location: "Hiroshima",
      distance: 5.5,
      image: "images\建設現場作業.jpg",
      tags: ["高収入", "男性限定"],
    },
    {
      id: 9,
      title: "データ入力",
      salary: "950-1150",
      japaneseLevel: 4,
      location: "Sendai",
      distance: 0.8,
      image: "images\データ入力.jpeg",
      tags: ["PC作業", "在宅可"],
    },
    {
      id: 10,
      title: "倉庫ピッキング",
      salary: "1150-1350",
      japaneseLevel: 1,
      location: "Yokohama",
      distance: 2.3,
      image: "images\倉庫ピッキング.jpg",
      tags: ["フォークリフト作業", "賞与あり"],
    },
    {
      id: 11,
      title: "カフェスタッフ",
      salary: "1050-1200",
      japaneseLevel: 3,
      location: "Okinawa",
      distance: 1.1,
      image: "images\カフェスタッフ.jpg",
      tags: ["接客業務", "英語活用"],
    },
    {
      id: 12,
      title: "自動車整備補助",
      salary: "1350-1550",
      japaneseLevel: 2,
      location: "Nagasaki",
      distance: 3.7,
      image: "images\自動車整備補助.jfif",
      tags: ["技術習得", "車通勤可"],
    },
    {
      id: 13,
      title: "食品加工",
      salary: "1200-1400",
      japaneseLevel: 1,
      location: "Chiba",
      distance: 2.9,
      image: "images\食品加工.jpg",
      tags: ["冷蔵庫作業", "まかないあり"],
    },
    {
      id: 14,
      title: "イベントスタッフ",
      salary: "1250-1500",
      japaneseLevel: 2,
      location: "Osaka",
      distance: 1.5,
      image: "images\イベントスタッフ.png",
      tags: ["短期可", "日払い可"],
    },
    {
      id: 15,
      title: "保育補助",
      salary: "1100-1300",
      japaneseLevel: 3,
      location: "Tokyo",
      distance: 0.7,
      image: "images\保育補助.jfif",
      tags: ["子供好き", "保育士資格不要"],
    },
    {
      id: 16,
      title: "ビル清掃",
      salary: "1000-1200",
      japaneseLevel: 1,
      location: "Kyoto",
      distance: 2.4,
      image: "images\ビル清掃.jpg",
      tags: ["早朝勤務", "未経験OK"],
    },
    {
      id: 17,
      title: "農業作業",
      salary: "1300-1600",
      japaneseLevel: 1,
      location: "Hokkaido",
      distance: 6.0,
      image: "images\農業作業.jpg",
      tags: ["自然環境", "季節労働"],
    },
    {
      id: 18,
      title: "工場品質検査",
      salary: "1150-1350",
      japaneseLevel: 2,
      location: "Toyota",
      distance: 3.1,
      image: "images\工場品質検査.jpg",
      tags: ["細かい作業", "女性活躍中"],
    },
    {
      id: 19,
      title: "宅配便仕分け",
      salary: "1400-1700",
      japaneseLevel: 1,
      location: "Tokyo",
      distance: 4.2,
      image: "images\宅配便仕分け.jpg",
      tags: ["夜間勤務", "体力仕事"],
    },
    {
      id: 20,
      title: "ホールスタッフ",
      salary: "1050-1250",
      japaneseLevel: 3,
      location: "Osaka",
      distance: 1.3,
      image: "images\ホールスタッフ.jpg",
      tags: ["飲食店", "接客メイン"],
    }
  ];